server:
  port: 9999
spring:
  application:
    name: product-search
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seo
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
