server:
  port: 9999
spring:
  application:
    name: e-commerce-application
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB







