server:
  port: 8899

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/seo
      host: localhost
      port: 27017
      database: seo
    redis:
      host: localhost
      port: 6378
  elasticsearch:
    rest:
      uris: localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/seo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: anh1710gdt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 1000

application:
  elastic:
    port: 9200
    host: localhost
    scheme: http

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG

api:
  prefix: /api/v1
  version: 1.0.0